apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrez
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starrez
  template:
    metadata:
      labels:
        app: starrez
    spec:
      containers:
      - name: starrez
        image: catherinevee/starrez:1.01
        ports:
        - containerPort: 31916
---
apiVersion: v1
kind: Service
metadata:
  name: starrez-entrypoint
  namespace: development
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  selector:
    app: starrez
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 31916
    name: http
  - port: 443
    targetPort: 31917
    name: https
