apiVersion: apps/v1
kind: Deployment
metadata:
  name: catstar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catstar
  template:
    metadata:
      labels:
        app: catstar
    spec:
      containers:
      - name: catstar
        image: catherinevee/starrez:1.01
        ports:
        - containerPort: 31916
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
