apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrez
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starrez
  template:
    metadata:
      labels:
        app: starrez
    spec:
      containers:
      - name: starrez
        image: nginx
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: starrez-entrypoint
  namespace: development
spec:
  type: NodePort
  selector:
    app: starrez
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
