apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starrez-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - catherine.it.com
    secretName: catherine.it.com-seckey
  rules:
  - host: catherine.it.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: starrez
            port:
              number: 31916
---
apiVersion: v1
kind: Service
metadata:
  name: starrez
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 31916
  selector:
    app: starrez
