name: Docker Build

on: [push, pull_request]

jobs:
  docker:
    environment: cathprompt_dev_env    
    runs-on: ubuntu-latest
    env:
      cwd: docker/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      # Build the Docker image
      - name: Build Docker image
        run: docker build -t catherinevee/catprompt:${{ github.sha }} .
        working-directory: $cwd

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6

        with:
          context: .
          push: true
          tags: catherinevee/catprompt:latest
          working-directory: $working-directory/
