name: Docker Build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Step 2: Use npm caching for faster dependency installs.

      - name: Install Node.js dependencies
        run: npm ci # Step 3: Perform a clean install of Node.js dependencies.
        working-directory: docker/

      - name: Run tests
        run: npm test #
      # Build the Docker image
      - name: Build Docker image
        run: docker build -t catherinevee/catprompt:${{ github.sha }} .
        working-directory: docker/
      # Test the built image
      - name: Test Docker image
        run: |
          docker run --rm catherinevee/catprompt:${{ github.sha }} npm run dev

      # Save the image for deployment (optional)
      - name: Save Docker image
        run: |
          docker save catherinevee/catprompt:${{ github.sha }} | gzip > catprompt.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: catprompt.tar.gz
